### ISSUE TITLE
Show quit/part messages when user has said something in IRC channel

### ISSUE THREAD

**Issue by n0ur** [munichmakerlab/RelayBot#2]
@tiefpunkt as reported, this feature isn't working yet! But we will fix it very soon!

Could you perhaps check the production relaybot.config, and tell me what modes are the bots running on (Default, SilentJoinPart, etc)? I think I know the problem but I need to make sure first before I add any new code.

Thank you!

**Comment by tiefpunkt** [comment]
Just checked it again, and it actually seems to work now. I guess we marked it as "not working" because of the connection issues we had with the hackint network, and I then reverted back to the old version.

However, if you want to add more code, here's the relaybot.config:

```
[DEFAULT]
#Twisted's default is 30 seconds.
timeout=120
port=6697
channel=#a-bridged-channel
nick=Bot
##Can change to allow more specialized behavior.
mode=Default
##Response sent when addressed with <nickname>: or privmsg'd.
info=This is a relay bot.
username=RelayBot
realname=Relay P. Botterson
heartbeat=90

[flowdock]
host=irc.flowdock.com
channel=#mumalab/main
nick=IRC
mode=NickServ
info=This is a relay bot between IRC and Flowdock
username=xxxx@xxxx.xxx
nickServPassword=xxxxxxxxxxxxxxx

[hackint]
host=irc.hackint.eu
channel=#munichmakerlab
nick=flowdock
mode=SilentJoinPart
```
